<?php 
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CompositeFault implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var Fault|null[] $faults public property
     */
    public $faults;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array|null        $faults   Initialization value for the property $this->faults
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->faults = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['faults'] = $this->faults;

        return $json;
    }
}