<?php
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class Day10Enum {
    /**
     * TODO: Write general description for this element
     */
    const MO = "MO";

    /**
     * TODO: Write general description for this element
     */
    const TU = "TU";

    /**
     * TODO: Write general description for this element
     */
    const WE = "WE";

    /**
     * TODO: Write general description for this element
     */
    const TH = "TH";

    /**
     * TODO: Write general description for this element
     */
    const FR = "FR";

    /**
     * TODO: Write general description for this element
     */
    const SA = "SA";

    /**
     * TODO: Write general description for this element
     */
    const SU = "SU";

}