<?php
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class DayEnum {
    /**
     * TODO: Write general description for this element
     */
    const WEEKDAY = "WEEKDAY";

    /**
     * TODO: Write general description for this element
     */
    const ALLWEEK = "ALLWEEK";

    /**
     * TODO: Write general description for this element
     */
    const MONDAY = "MONDAY";

    /**
     * TODO: Write general description for this element
     */
    const TUESDAY = "TUESDAY";

    /**
     * TODO: Write general description for this element
     */
    const WEDNESDAY = "WEDNESDAY";

    /**
     * TODO: Write general description for this element
     */
    const THURSDAY = "THURSDAY";

    /**
     * TODO: Write general description for this element
     */
    const FRIDAY = "FRIDAY";

    /**
     * TODO: Write general description for this element
     */
    const SATURDAY = "SATURDAY";

    /**
     * TODO: Write general description for this element
     */
    const SUNDAY = "SUNDAY";

}