<?php 
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DropOffTimeDatas implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var DropOffTimeDataDto|null[] $dropOffTimeData public property
     */
    public $dropOffTimeData;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array|null        $dropOffTimeData   Initialization value for the property $this->dropOffTimeData
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->dropOffTimeData = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['dropOffTimeData'] = $this->dropOffTimeData;

        return $json;
    }
}