<?php 
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DropOffTimeDataDto implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $day public property
     */
    public $day;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $latestTime public property
     */
    public $latestTime;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $day          Initialization value for the property $this->day       
     * @param   string            $latestTime   Initialization value for the property $this->latestTime
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->day        = func_get_arg(0);
            $this->latestTime = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['day']        = $this->day;
        $json['latestTime'] = $this->latestTime;

        return $json;
    }
}