<?php 
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Fault implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $explanationText public property
     */
    public $explanationText;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $faultCode public property
     */
    public $faultCode;

    /**
     * @todo Write general description for this property
     * @var ParamValue|null[] $paramValues public property
     */
    public $paramValues;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $explanationText   Initialization value for the property $this->explanationText
     * @param   string            $faultCode         Initialization value for the property $this->faultCode      
     * @param   array|null        $paramValues       Initialization value for the property $this->paramValues    
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->explanationText = func_get_arg(0);
            $this->faultCode       = func_get_arg(1);
            $this->paramValues     = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['explanationText'] = $this->explanationText;
        $json['faultCode']       = $this->faultCode;
        $json['paramValues']     = $this->paramValues;

        return $json;
    }
}