<?php 
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class OpeningHoursDto implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string|null $day public property
     */
    public $day;

    /**
     * @todo Write general description for this property
     * @var string|null $from1 public property
     */
    public $from1;

    /**
     * @todo Write general description for this property
     * @var string|null $from2 public property
     */
    public $from2;

    /**
     * @todo Write general description for this property
     * @var string|null $to1 public property
     */
    public $to1;

    /**
     * @todo Write general description for this property
     * @var string|null $to2 public property
     */
    public $to2;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string|null       $day     Initialization value for the property $this->day  
     * @param   string|null       $from1   Initialization value for the property $this->from1
     * @param   string|null       $from2   Initialization value for the property $this->from2
     * @param   string|null       $to1     Initialization value for the property $this->to1  
     * @param   string|null       $to2     Initialization value for the property $this->to2  
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->day   = func_get_arg(0);
            $this->from1 = func_get_arg(1);
            $this->from2 = func_get_arg(2);
            $this->to1   = func_get_arg(3);
            $this->to2   = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['day']   = $this->day;
        $json['from1'] = $this->from1;
        $json['from2'] = $this->from2;
        $json['to1']   = $this->to1;
        $json['to2']   = $this->to2;

        return $json;
    }
}