<?php 
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ParamValue implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $param public property
     */
    public $param;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $value public property
     */
    public $value;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $param   Initialization value for the property $this->param
     * @param   string            $value   Initialization value for the property $this->value
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->param = func_get_arg(0);
            $this->value = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['param'] = $this->param;
        $json['value'] = $this->value;

        return $json;
    }
}