<?php
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class ReturntypeEnum {
    /**
     * TODO: Write general description for this element
     */
    const JSON = "json";

    /**
     * TODO: Write general description for this element
     */
    const XML = "xml";

}