<?php 
/*
 * Api2PostnordComFindNearbyServicePointsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/29/2016
 */

namespace Api2PostnordComFindNearbyServicePointsLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ServicePointInformationResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var CompositeFault|null $compositeFault public property
     */
    public $compositeFault;

    /**
     * @todo Write general description for this property
     * @var CoordinateDto|null $coordinate public property
     */
    public $coordinate;

    /**
     * @todo Write general description for this property
     * @var string|null $customerSupportPhoneNo public property
     */
    public $customerSupportPhoneNo;

    /**
     * @todo Write general description for this property
     * @var ServicePointDto|null[] $servicePoints public property
     */
    public $servicePoints;

    /**
     * Constructor to set initial or default values of member properties
     * @param   CompositeFault|null   $compositeFault           Initialization value for the property $this->compositeFault        
     * @param   CoordinateDto|null   $coordinate               Initialization value for the property $this->coordinate            
     * @param   string|null       $customerSupportPhoneNo   Initialization value for the property $this->customerSupportPhoneNo
     * @param   array|null        $servicePoints            Initialization value for the property $this->servicePoints         
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->compositeFault         = func_get_arg(0);
            $this->coordinate             = func_get_arg(1);
            $this->customerSupportPhoneNo = func_get_arg(2);
            $this->servicePoints          = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['compositeFault']         = $this->compositeFault;
        $json['coordinate']             = $this->coordinate;
        $json['customerSupportPhoneNo'] = $this->customerSupportPhoneNo;
        $json['servicePoints']          = $this->servicePoints;

        return $json;
    }
}